### ISSUE TITLE
[✨ Feature request]: Add formula 4.2 from NEN_EN_1992_1_1_C2_2011

### ISSUE THREAD

**Issue by SZeltaat** [Blueprints-org/blueprints#265]
### Description

![image](https://github.com/Blueprints-org/blueprints/assets/111974143/a9fa15bc-dbca-44ce-8932-c535cf698416)

### Acceptance Criteria

- [ ] Add the formula to the code
- [ ] Add latex expression to the formula
- [ ] Add unittests
- [ ] Add docstrings
- [ ] Update table in docs with :heavy_check_mark:

### Confirmation

- [ ] I have checked that this feature does not already exist in the issue tracker.
- [ ] I have read and understood the contribution guidelines.

**Comment by PabloVasconez** [comment]
Close since it was already implemented.
