### ISSUE TITLE
[✨ Feature request]: Add formula 8.5 from NEN_EN_1992_1_1_C2_2011

### ISSUE THREAD

**Issue by MaartenBW** [Blueprints-org/blueprints#344]
### Description

Add formula 8.5 from NEN_EN_1992_1_1_C2_2011

### Acceptance Criteria

- [x]  Add the formula to the code
- [x]  Add latex expression to the formula
- [x]  Add unittests
- [x]  Add docstrings
- [x]  Update table in docs with ✔️

### Confirmation

- [X] I have checked that this feature does not already exist in the issue tracker.
- [X] I have read and understood the contribution guidelines.

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
