### ISSUE TITLE
[❓ Question]: Add a short title of your question.

### ISSUE THREAD

**Issue by Keesedc** [Blueprints-org/blueprints#404]
### Preliminary Checks

- [X] I have read the project documentation.
- [X] I have searched the issue tracker for similar questions.

### What Have You Tried?

I tried to download blue-prints with pip but enountered an error

### Question Description

C:\users\kees>pip install blue-prints
and the error is
error: No matching distribution found for blue-prints

### Confirmation

- [X] I have checked that this question does not already exist in the issue tracker or documentation.
- [X] I have read and understood the contribution guidelines.

**Comment by bro-wi** [comment]
Hi Keesedc,

Thank you for showing interest in blueprints!

What python version are you using? 

Currently we are only supporting 3.12 and greater. So this could be the issue that you cannot find a distribution.

Regards, Wichard

**Comment by bro-wi** [comment]
BTW: You can check your current python version by typing:
`python --version`
into your terminal

**Comment by Keesedc** [comment]
I use Python 3.9.19 (main, May  6 2024, 20:12:36) [MSC v.1916 64 bit (AMD64)]

Oke thank for jour solution. I shall update pyhton.

Regards, Kees

**Comment by bro-wi** [comment]
Great, that can do no harm as python 3.9 will reach end of life 31 Oct 2025 anyway and now not is actively maintained apart from security patches. I will close the issue as it is solved.
