### ISSUE TITLE
[✨ Feature request]: Latex representation of formula

### ISSUE THREAD

**Issue by johan-tuls** [Blueprints-org/blueprints#41]
### Description

Each formula will, for traceability and verifiability purposes, need someway to represent itself. 

### Acceptance Criteria

- [ ] It should give a Latex representation of the Symbol = Original formula = Numeric formula = Result
- [ ] Symbel only
- [ ] Formula symbolic
- [ ] Formula Numeric
- [ ] Result
- [ ] Adjust decimals

(Nice to have's ? )
- [ ] Show Units for the result only
- [ ] Show Units for each argument
- [ ] Avoid defining logic in different places, this should be the responsibility of the _evaluate method

### Dependencies

Python only, however Latex syntax. So in the future adapters could be written from Latex --> external packages.

### Confirmation

- [X] I have checked that this feature does not already exist in the issue tracker.
- [X] I have read and understood the contribution guidelines.

**Comment by egarciamendez** [comment]
Looking good 🚀 And extra nice to have would be the option to add the formula label at the end.
